services:

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'

  redis:
    image: 'redis:latest'
    container_name: redis

  spm:
    build:
      context: .
    container_name: spm
    volumes:
      - ./storage:/app/storage
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - SPM_AUTH_KEY=REPLACE_WITH_YOUR_PRIVATE_KEY
      - SPM_LOCAL_STORAGE_PATH=/app/storage
    ports:
      - 80:8080
