# For development only
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '0.0.0.0:5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '0.0.0.0:6379:6379'
